### ISSUE TITLE
Petite demande

### ISSUE THREAD

**Issue by Arias800** [TmpName/Fichier_en_vrac#1]
Salut @TmpName,
Comme je n'ai pas d'autres moyens de te contacter, je me permets de tricher un peu.
Est-ce que tu pourrais supprimer l'issue nommée "Clone wflx" du Github de Vstream ? (c'est celle où Sizanic et Che-Debaras se sont entre tuer).

Che-Debaras était venu me voir en mp, et on est d'accord sur le fait que c'est 'le meilleur truc à faire.
J'ai demandé à Sizanic, mais il a ignoré ma demande, donc je présume qu'il est contre.
C'est pour ça que je te contacte de manière plus "priver" pour cette demande.

**Comment by TmpName** [comment]
Che a deja supprimé tout ses commentaires, plus vraiment utile de la garder.
C'est bon c'est nettoyé.

**Comment by Arias800** [comment]
Parfait, merci.
